mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from polls import views

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='site_index'),
    url(r'^accounts/', include('django.contrib.auth.urls')),

]

mysite/polls/urls.py
from django.conf.urls import url
from . import views


app_name = 'polls'

urlpatterns = [

    # /Equipe/
    url(r'^$', views.index, name='index'),

    # /Equipe/712
    url(r'^(?P<id>[0-9]+)/$', views.detail, name='detail'),


]

mysite/polls/models.py
from django.db import models



# Create your models here.
class Equipe(models.Model):
    id = models.IntegerField(primary_key=True)
    nom = models.CharField(max_length=250)
    drapeau = models.CharField(max_length=250)


    def __str__(self):
        return self.nom + ' - ' + self.drapeau

class Joueur(models.Model):
    id = models.IntegerField(primary_key=True)
    nom = models.CharField(max_length=250)
    present = models.BooleanField(default= False)
    equipe_id = models.ForeignKey(Equipe, on_delete=models.CASCADE)


    def __str__(self):
        return self.nom

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Equipe, Joueur


def index(request):
    all_equipes = Equipe.objects.all()
    return render (request,'polls/index.html',{'all_equipes': all_equipes})

def detail(request, id):

    equipe = get_object_or_404(Equipe, pk=id)
    return render(request,'polls/detail.html',{'equipe': equipe})


def register(request):
    form = UserCreatForm()
    context = {'form':form}
    return render(request,'registration/register.html',context)

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title {% block title%}>Tunisiefoot {% endblock%}</title>
    {% load staticfiles %}
    <link rel= "stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <link  href="https://fonts.googleapis.com/css?family=Satisfy" rel= "stylesheet" type="text/css" />
    <link rel= "stylesheet" type="text/css" href="{% static 'equipe/style.css' %}"/>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'polls:index' %}">Tunisiefoot</a>

        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">

                <li class="active">
                    <a href="{% url 'polls:index'%}">
                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp; Equipe


                    </a>

                </li>
                <li class="">
                    <a href="#"%>
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp; Joueur


                    </a>

                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default"> Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#"%>
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Ajouter Equipe

                    </a>

                </li>
                <li class="">
                    <a href="#"%>
                        <span class="glyphicon glyphicon-on" aria-hidden="true"></span>&nbsp; Login

                    </a>

                </li>
                <li class="">
                    <a href="#"%>
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout

                    </a>

                </li>

            </ul>

        </div>

    </div>

</nav>

{% block body%}
{% endblock%}
</body>
</html>

mysite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block title%}>Equipe Info {% endblock%}
{% block body%}

    {% load staticfiles %}
        <link rel= "stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
        <link  href="https://fonts.googleapis.com/css?family=Satisfy" rel= "stylesheet" type="text/css" />
        <link rel= "stylesheet" type="text/css" href="{% static 'equipe/style.css' %}"/>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


    <h1>{{equipe.nom}}</h1>
    <h3>{{equipe.drapeau}}</h3>

    <ul>
        {% for joueur in equipe.joueur_set.all %}
        <li>{{joueur.nom}} </li>
        {% endfor %}
    </ul>

    {% if error_message %}
        <p><strong>{{error_message}}</strong></p>
    {% endif %}


{% endblock%}

mysite/polls/templates/polls/equipe_form.html
{% extends 'polls/base.html' %}
{% block body%}{% endblock %}

{% block body%}

    {% if all_equipes %}
        <h3>Here are all my equipes :</h3>

        <ul>
            {% for equipe in all_equipes %}
                <li><a href="{% url 'polls:detail' equipe.id%}">{{ equipe.nom }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>Empty</h3>
    {% endif %}
{% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}


{% block body%}

    {% if all_equipes %}
        <h3>Here are all my team :</h3>

        <ul>
            {% for equipe in all_equipes %}
                <li><a href="{% url 'polls:detail' equipe.id%}">{{ equipe.nom }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>Empty</h3>
    {% endif %}
{% endblock %}